### ISSUE TITLE
How to use gremlin plugin in neo4j 3.x?

### ISSUE THREAD

**Issue by zhujiajunup** [neo4j-contrib/gremlin-plugin#43]
gremlin-plugin only support neo4j 2.x，I want to use gremlin plugin for neo4j server 3.4.11，how can I get a plugin for this version.

**Comment by x007007007** [comment]
I have a same question. This project last update is 3 years ago. Is this project still maintaining?

**Comment by jexp** [comment]
Good point. No it was for TP2.

Look at using TP server with gremlin-neo4j
